name: subtitle_wrapper_package_with_txvod
description: A Subtitle Wrapper package, this subtitle wrapper package displays subtitles for a video player.
version: 2.2.0
homepage: https://github.com/Joran-Dob/flutter_subtitle_wrapper

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  http_parser: ^4.0.1
#  video_player: ^2.4.2
  super_player:
    git:
      url: https://github.com/LiteAVSDK/Player_Flutter
      path: Flutter

dev_dependencies:
  bloc_test: ^9.0.3
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1
  mocktail: ^0.3.0

flutter:
